### ISSUE TITLE
THIS IS A QUESTION ON WINDOWS

### ISSUE THREAD

**Issue by mikeNike9** [ifm/libo3d3xx#103]
Hello all

I have had some issues with AC power failure in some locations.
This AC power failure will sometimes freeze the cameras.
I will be able to connect to the camera successfully but when the camera is updated via pmdUpdate(); 
the windows sdk gets tied up and will not return the object PMD_OK.

I fix this issue by rebooting the camera.

I would like to create a script to reboot all of my cameras in my system when this situation occurs so the system will fix itself rather than either me rebooting via the vision assistant or physically powering it down for 15-30 seconds.

I know there are command line tools for linux but I was aware of any in Windows.
I have a note into Germany but wanted to reach out here on the forum and see if you any of you guys had any ideas.

thank you 

mike Jr

FreightSnap LLC

**Comment by graugans** [comment]
Hello @mikeNike9,
We have recently added [Microsoft Windows support](https://github.com/lovepark/ifm3d/blob/master/doc/windows.md) for the camera module on the [ifm3d](https://github.com/lovepark/ifm3d) library which is the successor of the libo3d3xx. Discussion and feedback about this feature takes place in this issue [#21](https://github.com/lovepark/ifm3d/issues/21) any feedback is appreciated.

**Comment by mikeNike9** [comment]
I see!!! Im excited to test it out!

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
