### ISSUE TITLE
 Pre Req and also to make the o3d3x-viewer work.

### ISSUE THREAD

**Issue by mikeNike9** [ifm/libo3d3xx#106]
@graugans @tpanzarella 

For Ubuntu 16.04 you'll need at least the following packages:
first do this 
sudo apt-get install libboost-all-dev \
    libgtest-dev \
    libgoogle-glog-dev \
    libxmlrpc-c++8-dev \
    libopencv-dev \
    libpcl-dev \
    build-essential \
    cmake

if you wnat viewer to work do the next steps.
These are straight from ros

1.   sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

2.  sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

3. sudo apt-get update

4.  sudo apt-get install ros-kinetic-desktop-full

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
