### ISSUE TITLE
Please Add Global Test Disable Flag

### ISSUE THREAD

**Issue by Jmeyer1292** [ifm/libo3d3xx#114]
Please add a global cmake flag that disables all unit tests that require hardware. The desired work flow would be to build all submodules with the cmake -DNO_TESTS, make process.

I understand I can do it step by step, but it's a real pain to deploy on new computers and or to setup automatic build scripts. The current default requirement to configure your pc network, backup hardware, wipe hardware, build, run tests, restore settings seems a little burdensome.

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
