### ISSUE TITLE
issue with building the oem partition

### ISSUE THREAD

**Issue by mikeNike9** [ifm/libo3d3xx#116]
Here is the out put that has the error.
from first glance seems that 

CMake Error at CMakeLists.txt:68 (find_package):
  By not providing "Findresultsync.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "resultsync", but CMake did not find one.

  Could not find a package configuration file provided by "resultsync"
  (requested version 0.2) with any of the following names:

    resultsyncConfig.cmake
    resultsync-config.cmake

  Add the installation prefix of "resultsync" to CMAKE_PREFIX_PATH or set
  "resultsync_DIR" to a directory containing one of the above files.  If
  "resultsync" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/mike/libo3d3xx/modules/oem/build/CMakeFiles/CMakeOutput.log".
See also "/home/mike/libo3d3xx/modules/oem/build/CMakeFiles/CMakeError.log".

find_package(resultsync 0.2 REQUIRED) line 68

Where do I get this package.
Or do I even need it.

**Comment by mikeNike9** [comment]
I cannot seem to find Lib_resultsync anywhere in my filesystem.
Was this something that should have been sourced when I initially build the environment because I am using an older version of  poky-glibc-i686-vantage-image-armv7ahf-vfp-neon-toolchain-qte-1.8.1.sh.
This script was given to me along with the gem tool months ago though.

**Comment by graugans** [comment]
@mikeNike9 there is no need to rebuild the resultsync library by zour own this is already included in the latest firmware release and within the matching toolchain. So it is maybe needed to update the firmware plus the toolchain. Sorry I can not provide any of them because I am out of office until January the 8th. But zou can contact Ville who will be in the office starting with the 2nd of January.

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
