### ISSUE TITLE
 std::condition_variable does not use monotonic clock

### ISSUE THREAD

**Issue by graugans** [ifm/libo3d3xx#122]
The [WaitForFrame](https://github.com/lovepark/libo3d3xx/blob/master/modules/framegrabber/src/libo3d3xx_framegrabber/frame_grabber.cpp#L189) method in the framegrabber uses a std::condition_variable which can use the system clock as a reference which can lead to unexpected behaviours like hanging for a long time or returning WaitForFrame with NULL.  See this github issue for [reference](https://github.com/logcabin/logcabin/issues/24) It is also stated in the [online c++ reference](http://en.cppreference.com/w/cpp/thread/condition_variable/wait_until).

**Comment by theseankelly** [comment]
@graugans correctly pointed out that the fix to ifm3d (https://github.com/ifm/ifm3d/pull/180) should be backported to libo3d3xx.
