### ISSUE TITLE
Failed to "Building the image module" @make

### ISSUE THREAD

**Issue by jimmyzmag** [ifm/libo3d3xx#129]
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
--   system
-- Found OpenCV: /opt/ros/kinetic (found suitable version "3.3.1", minimum required is "3") 
-- OpenCV_DIR: /opt/ros/kinetic/share/OpenCV-3.3.1-dev
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- DEB_FILE: libo3d3xx-image_0.7.5_ubuntu-16.04.5_amd64.deb
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jimmy/software/libo3d3xx/modules/image/build
jimmy@MSA02827U:~/software/libo3d3xx/modules/image/build$ make
Scanning dependencies of target o3d3xx_image
[  7%] Building CXX object src/libo3d3xx_image/CMakeFiles/o3d3xx_image.dir/image.cpp.o
[  7%] Built target o3d3xx_image
Scanning dependencies of target o3d3xx_image_static
[ 14%] Linking CXX static library libo3d3xx_image_static.a
[ 14%] Built target o3d3xx_image_static
Scanning dependencies of target o3d3xx_image_shared
[ 21%] Linking CXX shared library libo3d3xx_image.so
[ 21%] Built target o3d3xx_image_shared
Scanning dependencies of target o3d3xx-viewer_automoc
[ 28%] Automatic moc for target o3d3xx-viewer
[ 28%] Built target o3d3xx-viewer_automoc
Scanning dependencies of target o3d3xx-viewer
[ 35%] Building CXX object src/bin/CMakeFiles/o3d3xx-viewer.dir/o3d3xx-viewer.cpp.o
[ 42%] Building CXX object src/bin/CMakeFiles/o3d3xx-viewer.dir/o3d3xx-viewer_automoc.cpp.o
[ 50%] Linking CXX executable o3d3xx-viewer
/usr/bin/ld: cannot find -lvtkRenderingFreeTypeOpenGL
collect2: error: ld returned 1 exit status
src/bin/CMakeFiles/o3d3xx-viewer.dir/build.make:611: recipe for target 'src/bin/o3d3xx-viewer' failed
make[2]: *** [src/bin/o3d3xx-viewer] Error 1
CMakeFiles/Makefile2:241: recipe for target 'src/bin/CMakeFiles/o3d3xx-viewer.dir/all' failed
make[1]: *** [src/bin/CMakeFiles/o3d3xx-viewer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
jimmy@MSA02827U:~/software/libo3d3xx/modules/image/build$ ^C
jimmy@MSA02827U:~/software/libo3d3xx/modules/image/build$

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
