### ISSUE TITLE
Raspberry Pi 

### ISSUE THREAD

**Issue by MISSEY** [ifm/libo3d3xx#134]
How I can use ifm O3D303 with raspberry pi, I want to use it for image recognization.

**Comment by graugans** [comment]
Hey @MISSEY may I recommend switching to [ifm3d](https://github.com/ifm/ifm3d) which is the successor of libo3d3xx. In general it highly depends on what operating system your are planning to run on the Raspberry PI. Any Debian based recent version should not be of any Problem.

I recommend to build the library natively on the Raspberry Pi. If you face any issues please open a new Issue with the error and the used distribution.
