### ISSUE TITLE
Link to firmware results in a 404 error

### ISSUE THREAD

**Issue by pmulreid** [ifm/libo3d3xx#138]
https://github.com/lovepark/o3d3xx-firmware

**Comment by theseankelly** [comment]
Hey @pmulreid -- thanks for filing the issue. That repository has been deprecated. Official firmware releases can be found on the official ifm website:

https://www.ifm.com/us/en/downloadarea/DualisContent

Scroll down to find the "0100 Startup_Package_O3D3xx_Camera" package.

**Comment by theseankelly** [comment]
Also while you're here, this library is on a path toward deprecation (for some time now) -- the official supported client library is https://github.com/ifm/ifm3d
