### ISSUE TITLE
can you offer 16.04 *.deb

### ISSUE THREAD

**Issue by comwise** [ifm/libo3d3xx#139]
i tried build source code, but occur some problem,  can you offer ubuntu 16.04 *.deb directly? 
thanks for your reply

**Comment by theseankelly** [comment]
Hi @comwise -- I recommend you use our newer library, [ifm3d](https://github.com/ifm/ifm3d). The README `ifm3d` has instructions for setting up an apt repository for Ubuntu 16.04.

**Comment by comwise** [comment]
> Hi @comwise -- I recommend you use our newer library, [ifm3d](https://github.com/ifm/ifm3d). The README for `ifm3d` has instructions for setting up an apt repository for Ubuntu 16.04.

the ifm3d lib support o3d3xx-ros?  i build this ros project which need libo3d3xx lib?

**Comment by theseankelly** [comment]
libo3d3xx and o3d3xx-ros go together, ifm3d and ifm3d-ros go together. So yes `ifm3d-ros` is built on top of `ifm3d` and supports the O3D3XX and O3X cameras.

By the way, if you're using Kinetic or Melodic, we're in the ROS distribution. You can do `apt-get install ros-melodic-ifm3d` or `apt-get install ros-kinetic-ifm3d` to install the ROS driver and core `ifm3d` library.

**Comment by comwise** [comment]
@theseankelly thanks for your replay , ifm3d-ros is good for o3d3xx

**Comment by theseankelly** [comment]
Great! feel free to file issues over on those projects if you run into issues.
