### ISSUE TITLE
Seg Fault in Embedded Port - Resetting FrameGrabber w/o ImageBuffer

### ISSUE THREAD

**Issue by tpanzarella** [ifm/libo3d3xx#65]
A bug has been detected that causes a segmentation fault. There is an inconsistency between the behaviors of the on-camera embedded port of `libo3d3xx` and the "desktop" version. Specifically, on the embedded version, when changing PCIC schemas at runtime via `.reset(...)` on the `FrameGrabber` smart pointer, you must also `.reset()` the `ImageBuffer`. This is not required (so it seems) on desktop builds. This bug is being investigated on the [dev-0.4.7 branch](https://github.com/lovepark/libo3d3xx/tree/dev-0.4.7). A minimal example that can be used to duplicate this issue can be found [here](https://github.com/lovepark/libo3d3xx/blob/dev-0.4.7/modules/image/src/bin/o3d3xx-crash-test.cpp).

/cc: @graugans

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
