### ISSUE TITLE
Snapshot of point cloud matrix

### ISSUE THREAD

**Issue by CANorFlexRay** [ifm/libo3d3xx#97]
I need the point cloud matrix in a file.
I got it with following code but there are two problems.

_cv::FileStroage fs("file.yml", cv::FileStorage::WRITE);
fs << "yourMat" << buff->XYZImage();_

First problem:
In that file.yml there are 5453 lines and 12 rows. So I have 65436 values but I excepted 23232 (137 x 176).

My second problem is that I need a snapshot of that point cloud when something is changing.
For example the O3D302 scans an object. Than I need a snapshot and than I put a second object in view of  sensor. After the point cloud stops changing I need the second snapshot.

**Comment by graugans** [comment]
@CANorFlexRay For your second problem you may consider to change the Trigger modes. Either use a software trigger or a hardware button.

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
